<a href="https://colab.research.google.com/github/lanson94706/Study-Tensorflow-basic-/blob/main/Tensorflow_basic(%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4_%EC%98%88%EC%A0%9C%ED%95%99%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측에 히든레이어 적용


In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
#독립변수, 종속 변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape) #데이터의 형태가 어떠한지 항상 확인할 것, 버그를 줄일 수 있음

(506, 13) (506, 1)


In [ ]:
#모델 제작
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation ='swish')(X) ##
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 10)                140       
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#모델 학습
model.fit(독립, 종속, epochs = 1000, verbose=0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 24.6279
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 24.4814
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 22.5191
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 25.6890
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 24.1846
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 23.4837
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 24.5485
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 23.3730
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 23.0926
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 24.5634


In [ ]:
#모델 사용
print(model.predict(독립[:5]))
print(종속[:5])

[[32.100666]
 [25.535234]
 [31.981773]
 [31.647455]
 [30.308346]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류에 히든레이어 적용

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H) ##
H = tf.keras.layers.Dense(8, activation = 'swish')(H) ##
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy',
              metrics = 'accuracy')

In [ ]:
model.fit(독립, 종속, epochs = 100)
#학습이 되어가는 과정을 확인할 때는 accuracy를 확인하는 것보다 loss값을 확인하는 것이 바람직하다

In [ ]:
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9787498e-01 2.1249915e-03 1.2011961e-09]
 [9.9551767e-01 4.4823466e-03 9.9587449e-09]
 [9.9682570e-01 3.1742803e-03 5.4921037e-09]
 [9.9531108e-01 4.6888893e-03 1.2697701e-08]
 [9.9807417e-01 1.9258354e-03 1.0083641e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
