<a href="https://colab.research.google.com/github/lanson94706/Study-Tensorflow-basic-/blob/main/Tensorflow_basic(%EB%A0%88%EB%AA%A8%EB%84%A4%EC%9D%B4%EB%93%9C_%ED%8C%90%EB%A7%A4%EB%9F%89_%EC%98%88%EC%B8%A1_%EC%98%88%EC%A0%9C%ED%95%99%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
#데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
#종속변수, 독립변수
독립 = 데이터[{"온도"}]
종속 = 데이터[{'판매량'}]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
#모델 제작
X = tf.keras.layers.Input(shape=[1])   #입력받을 데이터 종류의 개수
Y = tf.keras.layers.Dense(1)(X)        
model = tf.keras.models.Model(X, Y)
model.compile(loss ='mse')

In [ ]:
#모델을 학습합니다
model.fit(독립, 종속, epochs = 10)
#1.4161 e-04는 10의 -4승 이라는 의미 1.4161 * 10의 -4승 하면 loss값이 나옴
# verbose를 이용하면 출력을 생략하고 학습을 할 수 있다

Epoch 1/10
1/1 [==============================] - 0s 13ms/step - loss: 5.8349e-04
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 5.8317e-04
Epoch 3/10
1/1 [==============================] - 0s 18ms/step - loss: 5.8279e-04
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 5.8230e-04
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 5.8191e-04
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 5.8140e-04
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 5.8098e-04
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 5.8063e-04
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 5.8022e-04
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 5.7986e-04


In [ ]:
#모델 이용
model.predict(독립)

array([[40.021687],
       [42.008923],
       [43.996162],
       [45.9834  ],
       [47.970634],
       [49.957874]], dtype=float32)

In [ ]:
종속

판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [ ]:
model.predict(독립)

array([[40.021687],
       [42.008923],
       [43.996162],
       [45.9834  ],
       [47.970634],
       [49.957874]], dtype=float32)

In [ ]:
model.predict([[15]])

array([[30.085495]], dtype=float32)